<?php get_header(); ?>
<section class="book-hero"><div class="wrap book-grid"><div><p class="kicker">A Cannon-Lear Publishing Title</p><h1>Executive<br>Knowledge<br>Management</h1><p class="subtitle">How Leaders Turn Data into Decisions in the Age of AI</p><p>A strategic guide for executives, senior leaders, directors, and decision-makers who need to improve how their organizations learn, decide, and act.</p><div class="buttons"><a class="btn" href="#platforms">Pre-order Details</a></div></div><img class="cover" src="<?php echo cannon_lear_asset('executive-knowledge-management-cover.png'); ?>" alt="Executive Knowledge Management book cover"></div></section>
<section class="book-preview" id="preview"><img class="preview-image" src="<?php echo cannon_lear_asset('book-preview.png'); ?>" alt="Preview pages from Executive Knowledge Management"></section>
<section class="paper section"><div class="wrap"><h2 class="section-title">Why This Book Matters</h2><div class="three-cols">
  <article class="matter"><?php cannon_lear_icon('▤'); ?><h3>Organizations have more data than ever</h3><p>But access alone has not consistently produced better decisions.</p></article>
  <article class="matter"><?php cannon_lear_icon('↔'); ?><h3>Critical knowledge does not move by itself</h3><p>It must be captured, governed, transferred, validated, and converted into organizational benefit.</p></article>
  <article class="matter"><?php cannon_lear_icon('◈'); ?><h3>AI magnifies both capability and weakness</h3><p>AI accelerates what organizations already have—including gaps in knowledge governance.</p></article>
</div></div></section>
<section class="dark section"><div class="wrap"><h2 class="section-title gold">Inside the Book</h2><div class="inside-grid">
<?php $chapters=[['Knowledge as an Executive Asset','Why knowledge management belongs in the executive agenda.'],['From Data to Decisions','How organizations convert information into judgment and action.'],['The Knowing–Doing Gap','Why knowledge does not automatically produce performance.'],['Knowledge Flow','How knowledge moves through decisions and operations.'],['Executive Leadership','The responsibilities leaders cannot delegate.'],['KM and AI','Why trusted knowledge is the prerequisite for trustworthy AI.']]; foreach($chapters as $c): ?><article class="chapter"><strong><?php echo esc_html($c[0]); ?></strong><p><?php echo esc_html($c[1]); ?></p></article><?php endforeach; ?>
</div></div></section>
<section class="paper section" id="resources"><div class="wrap"><h2 class="section-title">Executive Resources</h2><p style="text-align:center">Apply the concepts in this book with practical tools.</p><div class="resource-grid">
<?php $resources=[['Executive Sponsor Checklist','Download'],['Knowing–Doing Gap Diagnostic','Take Diagnostic'],['Executive Knowledge Flow Assessment','Assess'],['Eight Executive KM Responsibilities','Start Assessment'],['90-Day Executive KM Action Planner','Get the Planner']]; foreach($resources as $r): ?><article class="resource"><strong><?php echo esc_html($r[0]); ?></strong><a href="<?php echo esc_url(home_url('/contact/')); ?>"><?php echo esc_html($r[1]); ?></a></article><?php endforeach; ?>
</div></div></section>
<section class="paper section" id="platforms"><div class="wrap"><h2 class="section-title" style="text-align:left">Available<br>Platforms</h2><div class="platform-grid"><div class="platform"><strong>Amazon Kindle</strong><span>Coming Soon</span></div><div class="platform"><strong>Apple Books</strong><span>Coming Soon</span></div><div class="platform"><strong>Rakuten Kobo</strong><span>Coming Soon</span></div><div class="platform"><strong>Barnes &amp; Noble</strong><span>Coming Soon</span></div></div></div></section>
<?php get_footer(); ?>
